package com.pvk.app.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.redis.core.RedisHash;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@RedisHash("Product")
@DynamoDBTable( tableName = "products")
public class Product implements Serializable {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String pid;
    @DynamoDBAttribute
    private String pName;
    @DynamoDBAttribute
    private String pDesc;
    @DynamoDBAttribute
    private String pQty;
    @DynamoDBAttribute
    private String pPrice;
    @DynamoDBAttribute
    private Category category;



}
